---
- name: Alle Server aktualisieren
  # Wir zielen NUR auf laufende LXC Container
  hosts: proxmox_type_lxc:&proxmox_status_running
  
  # Wenn ein Server nicht erreichbar ist: Ignorieren statt Fehler werfen!
  ignore_unreachable: true
  
  # Verhindert den Absturz bei ausgeschalteten Containern beim Start
  gather_facts: false 

  become: true

  tasks:
    # Wir holen die Facts (OS Version etc) manuell nach, aber nur bei denen, die leben
    - name: Verbindung testen und Facts sammeln
      setup:
      ignore_errors: true

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      # Nur ausführen, wenn der Server wirklich erreichbar war
      when: ansible_facts is defined

    - name: Upgrade aller Pakete
      apt:
        upgrade: dist
      when: ansible_facts is defined

    - name: Unnötige Abhängigkeiten entfernen
      apt:
        autoremove: yes
      when: ansible_facts is defined
