---
- name: Alle Server aktualisieren
  hosts: all:!pve-01:!homeassistant:!NUT-debian12:!ansible-lxc:!donetick:!plex
  become: true  # Bedeutet: Führe Befehle als sudo/root aus

  tasks:
    - name: Update apt cache (wie 'apt-get update')
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade aller Pakete (wie 'apt-get upgrade')
      apt:
        upgrade: dist

    - name: Unnötige Abhängigkeiten entfernen (wie 'apt-get autoremove')
      apt:
        autoremove: yes

    - name: Prüfen ob Neustart nötig ist
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Server neu starten (falls nötig)
      reboot:
        msg: "Neustart durch Ansible nach Updates"
      when: reboot_required_file.stat.exists
