---
- name: Update Debian-based systems
  hosts: debian_hosts
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_update
      retries: 3
      delay: 10
      until: apt_update is success

    - name: Upgrade all packages
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes
      register: apt_upgrade
      retries: 3
      delay: 10
      until: apt_upgrade is success

    - name: Check if upgraded kernel is installed
      shell: dpkg -l | grep linux-image | grep ^ii | wc -l
      register: kernel_update
      changed_when: false

    - name: Check if services need restarting
      command: checkrestart
      register: services_check
      changed_when: false
      failed_when: false
      package: debian-goodies
      ignore_errors: true

    - name: Reboot system if required
      reboot:
        msg: "Reboot required after system updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists or kernel_update.stdout|int > 1

    - name: Show services that need restart
      debug:
        msg: "{{ services_check.stdout_lines }}"
      when: services_check.rc == 0 and services_check.stdout != ""

  handlers:
    - name: Restart changed services
      command: needrestart -r a
      when: services_check.rc == 0
