  hosts: proxmox
  become: true
  gather_facts: true
  
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Consider cache valid for 1 hour
      when: ansible_os_family == "Debian"
      
    - name: Upgrade all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"
