---
###############################################
# Playbook for my Proxmox VMs
###############################################
- name: ansible-first-01
  hosts: tautulli
  tasks:

    #####################
    # Update && Upgrade installed packages and install a set of base software
    #####################
    - name: Update apt package cache.
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600

    - name: Upgrade installed apt packages.
      ansible.builtin.apt:
        upgrade: 'yes'

    - name: Ensure that a base set of software packages are installed.
      ansible.builtin.apt:
        pkg:
         - htop
         - needrestart
         - python3-openssl
        state: latest


    #####################
    # Check for new kernel and reboot
    #####################
    - name: Check if a new kernel is available
      ansible.builtin.command: needrestart -k -p > /dev/null; echo $?
      register: result
      ignore_errors: yes

    - name: Restart the server if new kernel is available
      ansible.builtin.command: reboot
      when: result.rc == 2
      async: 1
      poll: 0

    - name: Wait for the reboot and reconnect
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
        timeout: 60
      connection: local

    - name: Check the Uptime of the servers
      shell: "uptime"
      register: Uptime

    - debug: var=Uptime.stdout


