- hosts: proxmox
  become: true
  roles:
    - geerlingguy.clamav
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: install htop package
      action: apt name=htop state=present update_cache=yes
