---
- name: Update Linux system
  hosts: all
  become: yes

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade packages
      apt:
        upgrade: dist-upgrade
