---
- name: Update and upgrade Linux systems
  hosts: all
  gather_facts: true
  
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Consider cache valid for 1 hour
      when: ansible_os_family == "Debian"
      
    - name: Upgrade all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"
      
    - name: Update package cache (RHEL/CentOS)
      dnf:
        update_cache: yes
      when: ansible_os_family == "RedHat"
      
    - name: Upgrade all packages (RHEL/CentOS)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      
    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"
      
    - name: Reboot system if required (Debian/Ubuntu)
      reboot:
        msg: "Rebooting system due to package updates"
        connect_timeout: 300
        reboot_timeout: 600
      when: 
        - ansible_os_family == "Debian"
        - reboot_required.stat.exists
      
    - name: Check if reboot is required (RHEL/CentOS)
      command: needs-restarting -r
      register: reboot_required_rhel
      failed_when: false
      changed_when: false
      when: ansible_os_family == "RedHat"
      
    - name: Reboot system if required (RHEL/CentOS)
      reboot:
        msg: "Rebooting system due to package updates"
        connect_timeout: 300
        reboot_timeout: 600
      when: 
        - ansible_os_family == "RedHat"
        - reboot_required_rhel.rc == 1

